# Generated by Django 2.2.10 on 2020-07-21 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0025_auto_20200721_2111'),
        ('students', '0025_auto_20200721_2235'),
    ]

    operations = [
    ]
